### PR TITLE
Customer controller

### PR DESCRIPTION
**Pull request by edwards-j**
## Link to Ticket
Closes [Customer Controller](https://github.com/NSS-Alleged-Donkeys/BangazonAPI/issues/2)

## Description of Proposed Changes
1. Created customer Model
1. Created customer Controller with full functionality

## Steps to Test

```sh
git fetch --all
git checkout customer-controller

GET http://localhost:5000/api/Customer
GET# http://localhost:5000/api/Customer/#
GET# http://localhost:5000/api/Customer/#?_includes=payment
GET# http://localhost:5000/api/Customer/#?_includes=products
GET q http://localhost:5000/api/Customer?q=j

POST http://localhost:5000/api/Customer
{
"FirstName": "Steve"
"LastName": "Jobs"
}

PUT http://localhost:5000/api/Customer#
{
"FirstName": "Steve"
"LastName": "Wozniak"
}

```

### CODE REVIEW

**Review by HelenChalmers — APPROVED** [review]
Looking good!  Make sure to add the sample object to the PR.

**Comment by kellycook301** [comment]
Things are working smoooooothly.

**Review by kellycook301 — APPROVED** [review]
Things are working smothly!

**Review by megducharme — APPROVED** [review]
Great job! 🔥

**Pull request merged**
