### PR TITLE
added producttype Constructor

### PR DESCRIPTION
**Pull request by HelenChalmers**
## Link to Ticket
Closes # [https://github.com/NSS-Alleged-Donkeys/BangazonAPI/issues/3]()

## Description of Proposed Changes
* Added ProductType Model 
* Added ProductType Controller

## Steps to Test

git fetch --all
git checkout -b ProductType

GET http://localhost:5000/api/ProductType
POST http://localhost:5000/api/ProductType
PUT http://localhost:5000/api/ProductType
DELETE http://localhost:5000/api/ProductType

## @Figamus, @kellycook301, @edwards-j and @megducharme Please Review

### CODE REVIEW

**Review by Figamus — APPROVED** [review]
All controller functions working properly. Approved.

**Comment by megducharme** [comment]
Looks good! There are a few syntax errors in your PR template. Can someone clean those up when you have a second?

**Comment by edwards-j** [comment]
Looks good!

**Comment by edwards-j** [comment]
Woohoo!

**Review by edwards-j — APPROVED** [review]
looks good!

**Pull request merged**
